name: osx-installer

on:
  workflow_dispatch:
    inputs:
      git-repository:
        description: The fork of git.git to use for building Git
        required: false
      git-ref:
        description: "Which ref to build Git from (default: the latest v<version> tag)"
        required: false
  # push:

env:
  GIT_REPOSITORY: "${{github.event.inputs.git-repository}}"
  GIT_REF: "${{github.event.inputs.git-ref}}"
  FALLBACK_GIT_REPOSITORY: https://github.com/git/git

  # `gettext` is keg-only
  LDFLAGS: -L/usr/local/opt/gettext/lib
  CFLAGS: -I/usr/local/opt/gettext/include
  # Link with cURL
  CURL_LDFLAGS: -lcurl
  # To make use of the catalogs...
  XML_CATALOG_FILES: /usr/local/etc/xml/catalog
  # Enable a bit stricter compile flags
  DEVELOPER: 1
  # For the osx-installer build
  OSX_VERSION: 10.15
  V: 1

  # For scalar testing
  INCLUDE_SCALAR: 1

jobs:
  build:
    runs-on: macos-latest
    outputs:
      with_scalar: ${{ steps.get_outputs.outputs.with_scalar }}    # Whether Scalar was built into this release
    steps:
      - uses: actions/checkout@v1
      - name: Install Git's dependencies
        run: |
          brew install autoconf automake asciidoc docbook xmlto
          brew link --force gettext
      - name: Clone git
        run: |
          git clone -n "${GIT_REPOSITORY:-$FALLBACK_GIT_REPOSITORY}" git &&
          cd git &&
          if test -z "$GIT_REF"
          then
            GIT_REF="$(git for-each-ref \
              --sort=-taggerdate --count=1 --format='%(refname)' 'refs/tags/v[0-9]*')" &&
            test -n "$GIT_REF" ||
            { echo "No eligible tag found" >&2; exit 1; }
          fi &&
          git fetch origin "$GIT_REF" &&
          git switch --detach FETCH_HEAD
      - name: Build GIT-VERSION-FILE and .tar.gz files
        run: |
          set -x
          PATH=/usr/local/bin:$PATH \
          make -C git -j$(sysctl -n hw.physicalcpu) GIT-VERSION-FILE dist dist-doc
      - name: Bundle .dmg
        run: |
          die () {
            echo "$*" >&2
            exit 1
          }

          VERSION="`sed -n 's/^GIT_VERSION = //p' <git/GIT-VERSION-FILE`"
          test -n "$VERSION" ||
          die "Could not determine version!"
          export VERSION

          ln -s git git-$VERSION

          mkdir -p build &&
          cp git/git-$VERSION.tar.gz git/git-manpages-$VERSION.tar.gz build/ ||
          die "Could not copy .tar.gz files"

          #### # drop the -isysroot `GIT_SDK` hack
          #### sed -i .bak -e 's/ -isysroot .(SDK_PATH)//' Makefile ||
          #### die "Could not drop the -isysroot hack"

          # make sure that .../usr/local/git/share/man/ exists
          sed -i .bak -e 's/\(tar .*-C \)\(.*\/share\/man\)$/mkdir -p \2 \&\& &/' Makefile ||
          die "Could not edit Makefile"

          # For debugging:
          #
          # cat Makefile
          # make vars

          PATH=/usr/local/bin:/System/Library/Frameworks:$PATH \
          make build/intel-x86_64-catalina/git-$VERSION/osx-built-keychain ||
          die "Build failed"

          PATH=/usr/local/bin:$PATH \
          make image ||
          die "Build failed"

          mkdir osx-installer &&
          mv *.dmg disk-image/*.pkg osx-installer/
      - name: Determine whether Scalar is included in the build
        run: |
          if (find ./stage/git-*/usr/local/git/bin/scalar); then
            echo "::set-output name=with_scalar::true"
          else
            echo "::set-output name=with_scalar::false"
          fi
        id: get_outputs
      - name: Upload osx-installer artifacts
        uses: actions/upload-artifact@v1
        with:
          name: osx-installer
          path: osx-installer

  test-scalar:
    if: needs.build.outputs.with_scalar == 'true'
    needs: build
    runs-on: macos-latest
    steps:
      - name: Install Scalar.NET
        run: |
          brew tap microsoft/git
          brew install --cask scalar
      - name: Download test installer
        uses: actions/download-artifact@v2
        with:
          name: osx-installer
          path: osx-installer
      - name: Run test
        run: |
          set -x

          # Verify Scalar.NET
          ls -l $(which scalar)

          # Create test repo
          scalar clone "${GIT_REPOSITORY:-$FALLBACK_GIT_REPOSITORY}" test-repo
          cd test-repo && scalar register && cd ..

          # List Scalar.NET registrations
          scalar list

          # Install the scalar package
          pkgpath=$(find ./osx-installer/*.pkg)
          sudo installer -verbose -pkg $pkgpath -target /

          # List homebrew package
          brew list --cask scalar || echo "Scalar not found!"

          # Verify Scalar C
          ls -l $(which scalar)

          # List Scalar C registrations
          scalar list

          # DEBUG: print install log
          tail -n 150 /var/log/install.log